/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_menu_listeE (void);
GtkWidget* create_ajout_listeE (void);
GtkWidget* create_afficher_liste_electorale (void);
GtkWidget* create_modifier_liste (void);
GtkWidget* create_vote (void);
GtkWidget* create_stats (void);
GtkWidget* create_supprimer_liste (void);
