/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *menu_listeE;
  GtkWidget *ajout_listeE;
  GtkWidget *afficher_liste_electorale;
  GtkWidget *modifier_liste;
  GtkWidget *vote;
  GtkWidget *stats;
  GtkWidget *supprimer_liste;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  menu_listeE = create_menu_listeE ();
  gtk_widget_show (menu_listeE);
  /*
ajout_listeE = create_ajout_listeE ();
  gtk_widget_show (ajout_listeE);
  afficher_liste_electorale = create_afficher_liste_electorale ();
  gtk_widget_show (afficher_liste_electorale);
  modifier_liste = create_modifier_liste ();
  gtk_widget_show (modifier_liste);
  vote = create_vote ();
  gtk_widget_show (vote);
  stats = create_stats ();
  gtk_widget_show (stats);
  supprimer_liste = create_supprimer_liste ();
  gtk_widget_show (supprimer_liste);
*/

  gtk_main ();
  return 0;
}

